#spring:
#  datasource:
#    # url: jdbc:postgresql://localhost:5432/ecomdb
#    url: jdbc:postgresql://localhost:5432/ecomdb?stringtype=unspecified&currentSchema=public&ApplicationName=ecom-application&TimeZone=Asia/Kolkata
#    username: embarkx
#    password: embarkx
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        time_zone: Asia/Kolkata
#server:
#  port: ${SERVER_PORT}
#
##spring:
#  application:
#    name: ORDER-SERVICE
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
##  data:
##    mongodb:
##      uri: ${MONGODB_URI}
##      uri: mongodb://localhost:27017/order
## the below credintaion is for actucter that management one
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
## ----- end of actular configuration ------------
#info:
#  app:
#    name: E-Commerce-App-OrderModel
#    description: Spring Boot Actuator Info Example
#    version: 1.0.0
#  developer:
#    name: Ritik Sharma
#    email: ritik@example.com
#
#app:
#  message: "Hello-order-auto-refresh"
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
# ============= above is for docker with postgree ==========
# ========== below is for mysql with local ===============
#server:
#  port: ${SERVER_PORT:8083}
#
#spring:
#  application:
#    name: ORDER-SERVICE
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/ecomdb
#    username: root          # 🔁 change if different
#    password: root          # 🔁 change if different
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      maximum-pool-size: 10
#      connection-timeout: 30000
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        jdbc:
#          time_zone: UTC
#        format_sql: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true
#
#info:
#  app:
#    name: E-Commerce-App-OrderModel
#    description: Spring Boot Actuator Info Example
#    version: 1.0.0
#  developer:
#    name: Ritik Sharma
#    email: ritik@example.com
#
#app:
#  message: "Hello-order-auto-refresh"
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

#logging:
#  level:
#    root: INFO
#    com.app_ecom.user: TRACE
#  file:
#    name: logs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7

## ============= below is for mysql with docker ===============
#server:
#  port: ${SERVER_PORT:8083}
#
#spring:
#  application:
#    name: ORDER-SERVICE
#
#  datasource:
#    url: jdbc:mysql://localhost:3308/ecomdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
#    username: embarkx
#    password: embarkx
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: mysql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#  health:
#    circuitbreakers:
#      enable: true
#    shutdown:
#      enabled: true
#  tracing:
#    sampling:
#      probability: 1.0
#info:
#  app:
#    name: E-Commerce-App-OrderModel
#    description: Spring Boot Actuator Info Example
#    version: 1.0.0
#  developer:
#    name: Ritik Sharma
#    email: ritik@example.com
#
#app:
#  message: "Hello-order-auto-refresh"
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#
#logging:
#  level:
#    root: INFO
#    com.app_ecom.user: TRACE
#  file:
#    name: logs/${spring.application.name}.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7
#
## configuration of cuickit bracker
#resilience4j:
#  circuitbreaker:
#    instances:
#      productService:
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        registerHealthIndicator: true
#  retry:
#    instances:
#      retryBreaker:
#        maxAttempts: 5
#        waitDuration: 500ms
#
#  ratelimiter:
#    instances:
#      retryBreaker:
#        limitForPeriod: 2
#        limitRefreshPeriod: 4s
#        timeoutDuration: 0
#
 ## ----------- for postgresQL with  docker ---
server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    #url: jdbc:postgresql://postgres:5432/ecomdb
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: embarkx
    password: embarkx
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

info:
  app:
    name: E-Commerce-App-OrderModel
    description: Spring Boot Actuator Info Example
    version: 1.0.0
  developer:
    name: Ritik Sharma
    email: ritik@example.com

app:
  message: "Hello-order-auto-refresh"

eureka:
  client:
    service-url:
#      defaultZone: http://eureka-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.app_ecom.order: TRACE
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

# ===============================
# Resilience4j Configuration
# ===============================
resilience4j:

  circuitbreaker:
    instances:
      productService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
  retry:
    instances:
      retryBreaker:
        maxAttempts: 5
        waitDuration: 500ms

  ratelimiter:
    instances:
      retryBreaker:
        limitForPeriod: 2
        limitRefreshPeriod: 4s
        timeoutDuration: 0

