    #server:
#  port: 8083
#
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/order
#      database: order
#  datasource:
    # url: jdbc:postgresql://localhost:5432/ecomdb
#    url: jdbc:postgresql://localhost:5432/order?stringtype=unspecified&currentSchema=public&ApplicationName=ecom-application&TimeZone=Asia/Kolkata
#    username: embarkx
#    password: embarkx

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database: postgresql
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          time_zone: Asia/Kolkata
server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  data:
    mongodb:
      uri: ${MONGODB_URI}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

info:
  app:
    name: E-Commerce-App-OrderModel
    description: Spring Boot Actuator Info Example
    version: 1.0.0
  developer:
    name: Ritik Sharma
    email: ritik@example.com
