#server:
#  port: 8080
#
#spring:
#  application:
#    name: apiGateWay
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/api/products/**
#
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/api/orders/**,/api/cart/**
#
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/api/users/**
#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway: TRACE
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  tracing:
#    sampling:
#      probability: 1.0

spring:
  application:
    name: apigateway-service
  config:
    import: optional:configserver:http://localhost:8888
