spring:
  application:
    name: notification
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:guest}
    connection-timeout: 30000
    ssl:
      enabled: ${RABBITMQ_SSL:true}
rabbitmq:
  exchange:
    name: order.exchange
  queue:
    name: order.queue
  routing:
    key: order.tracking
server:
  port: 8084
