server:
  port: 8888

spring:
  application:
    name: SpringCloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ritiksharmaji/SpringBoot-Cloud-Config-Server
          clone-on-start: true
          default-label: main
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
