

#  profiles:
#    active: prod

server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:DemoApp}

build:
  id: ${BUILD_ID:000}
  version: ${BUILD_VERSION:1.0.0}
  name: ${BUILD_NAME:default}
