spring:
  application:
    name: SpringConfigDemo
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: prod
server:
  port: ${SERVER_PORT:8080}   # fallback if env var not set

build:
  id: ${BUILD_ID:1001}
  version: ${BUILD_VERSION:1.0.0}
  name: ${BUILD_NAME:Default-Build}
management:
  endpoints:
    web:
      exposure:
        include: refresh